### PR TITLE
Fixes for Scenes/Groups attached to NFC and Geofencing

### PR DESCRIPTION
**Pull request by JVaassen**
Solved #427, I hope.
If a Scene was selected instead of a switch, in the Dismiss function, a check is done along the list of switches. 
See also explanation I typed to #427  (this was closed , but I think notes there show it doesn't work in all cases). 

The code I made was only reviewed by me.
(In my fork you see more branches than neccesary, still learning using GIT).
I don't have an IDE in place yet for compilation and testing.

### CODE REVIEW

**Comment by galadril** [comment]
Thanks, ill test your code!

**Comment by galadril** [comment]
codes looks good! i also did the same fix for qr code & speech settings screens
Thanks

**Comment by JVaassen** [comment]
Thanks for the updates.
I was not aware of the other 2 screens....
When do you expect a release ?

Regards
Jos

**Comment by galadril** [comment]
i was planning on a new build starting next week.. 
i don't have any time this weekend (if something fails..) so thats why i move it to next week

**Comment by JVaassen** [comment]
Hi Galadril,
I installed the new version on my phone and tested it.
Unfortunately it still doesn't work, same issue.
I am installing Android SDK to dig bit deeper. Only conclusion I can come up with is that the boolean "isSceneOrGroup" is never true.

**Comment by JVaassen** [comment]
SDK up and running
But all relevant features (Geo/Speech/NFC/QR) are part of premium version. My SDK runs Lite version only, without a clue how to change that to premium to debug this....
(USB port to my phone is broken so I also cannot run the full version on my phone and test from there).
Any ideas ?

**Comment by galadril** [comment]
You have to put the build variants to paid debug

Op 8 feb. 2018 22:44 schreef "JVaassen" <notifications@github.com>:

**Pull request merged**
