### PR TITLE
Dashboard - Use sorting from server

### PR DESCRIPTION
**Pull request by RoadXY**

### CODE REVIEW

**Comment by galadril** [comment]
By this change, you just fully remove the alphanummeric sorting.
Is that what we want?

Or do we build a setting in which they can choose what kind of sorting they like?

Or we make the listview drag&dropable so every phone user can specify their own sorting?

**Comment by RoadXY** [comment]
Only the sorting for the Dashboard so it will follow the server dashboard (as much as possible).

I can make it in settings that we, for now, can sort on alphabetical order or server order?
And later enhance with an option for custom sorting?

**Comment by galadril** [comment]
Yeah with a setting would be better i think

**Comment by RoadXY** [comment]
Already working on it :-D

**Comment by RoadXY** [comment]
et voilà :-D

**Comment by galadril** [comment]
Nice!

**Pull request merged**
